#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : influxdb
Version  : 5.2.0
Release  : 26
URL      : https://files.pythonhosted.org/packages/62/ff/f3927023d5ef2ee4156a54ff87757eaff1f630aed6c0c4fbd1c1413bfb88/influxdb-5.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/62/ff/f3927023d5ef2ee4156a54ff87757eaff1f630aed6c0c4fbd1c1413bfb88/influxdb-5.2.0.tar.gz
Summary  : InfluxDB client
Group    : Development/Tools
License  : MIT
Requires: influxdb-python3
Requires: influxdb-license
Requires: influxdb-python
Requires: python-dateutil
Requires: pytz
Requires: requests
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : cov-core-python
BuildRequires : coverage-python
BuildRequires : funcsigs-python
BuildRequires : nose-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dateutil-python
BuildRequires : python-mock-python
BuildRequires : python3-dev
BuildRequires : pytz-python
BuildRequires : requests-mock-python
BuildRequires : requests-python
BuildRequires : setuptools
BuildRequires : six

%description
===============

%package license
Summary: license components for the influxdb package.
Group: Default

%description license
license components for the influxdb package.


%package python
Summary: python components for the influxdb package.
Group: Default
Requires: influxdb-python3

%description python
python components for the influxdb package.


%package python3
Summary: python3 components for the influxdb package.
Group: Default
Requires: python3-core

%description python3
python3 components for the influxdb package.


%prep
%setup -q -n influxdb-5.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532468891
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/influxdb
cp LICENSE %{buildroot}/usr/share/doc/influxdb/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/influxdb/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
