#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : influxdb
Version  : 2.12.0
Release  : 10
URL      : https://pypi.python.org/packages/source/i/influxdb/influxdb-2.12.0.tar.gz
Source0  : https://pypi.python.org/packages/source/i/influxdb/influxdb-2.12.0.tar.gz
Summary  : InfluxDB client
Group    : Development/Tools
License  : MIT
Requires: influxdb-python
BuildRequires : cov-core-python
BuildRequires : coverage-python
BuildRequires : funcsigs-python
BuildRequires : nose-cov-python
BuildRequires : nose-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dateutil-python
BuildRequires : python-dev
BuildRequires : python-mock-python
BuildRequires : python3-dev
BuildRequires : pytz-python
BuildRequires : requests-mock-python
BuildRequires : requests-python
BuildRequires : setuptools
BuildRequires : six

%description
InfluxDB-Python is a client for interacting with InfluxDB_.
.. image:: https://travis-ci.org/influxdata/influxdb-python.svg?branch=master
:target: https://travis-ci.org/influxdata/influxdb-python

%package python
Summary: python components for the influxdb package.
Group: Default
Requires: nose-cov-python
Requires: nose-python
Requires: python-dateutil-python
Requires: pytz-python
Requires: requests-mock-python
Requires: requests-python

%description python
python components for the influxdb package.


%prep
%setup -q -n influxdb-2.12.0

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
