#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : influxdb
Version  : 5.2.2
Release  : 32
URL      : https://files.pythonhosted.org/packages/03/5e/d528d463bca6ff7fb9441df22d65890e39ebbb503e550c1030eef0863e52/influxdb-5.2.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/03/5e/d528d463bca6ff7fb9441df22d65890e39ebbb503e550c1030eef0863e52/influxdb-5.2.2.tar.gz
Summary  : Scalable datastore for metrics, events, and real-time analytics
Group    : Development/Tools
License  : MIT
Requires: influxdb-license = %{version}-%{release}
Requires: influxdb-python = %{version}-%{release}
Requires: influxdb-python3 = %{version}-%{release}
Requires: python-dateutil
Requires: pytz
Requires: requests
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : cov-core-python
BuildRequires : coverage-python
BuildRequires : funcsigs-python
BuildRequires : nose-python
BuildRequires : python-dateutil-python
BuildRequires : python-mock-python
BuildRequires : pytz-python
BuildRequires : requests-mock-python
BuildRequires : requests-python
BuildRequires : six

%description
InfluxDB-Python
===============
.. image:: https://travis-ci.org/influxdata/influxdb-python.svg?branch=master
:target: https://travis-ci.org/influxdata/influxdb-python
.. image:: https://readthedocs.org/projects/influxdb-python/badge/?version=latest&style
:target: http://influxdb-python.readthedocs.org/
:alt: Documentation Status

%package license
Summary: license components for the influxdb package.
Group: Default

%description license
license components for the influxdb package.


%package python
Summary: python components for the influxdb package.
Group: Default
Requires: influxdb-python3 = %{version}-%{release}

%description python
python components for the influxdb package.


%package python3
Summary: python3 components for the influxdb package.
Group: Default
Requires: python3-core

%description python3
python3 components for the influxdb package.


%prep
%setup -q -n influxdb-5.2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552593472
export LDFLAGS="${LDFLAGS} -fno-lto"
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/influxdb
cp LICENSE %{buildroot}/usr/share/package-licenses/influxdb/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/influxdb/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
